apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: simple-node-app
  template:
    metadata:
      labels:
        app: simple-node-app
    spec:
      containers:
      - name: simple-node-app
        image: your-dockerhub-username/simple-node-app:latest
        ports:
        - containerPort: 3000
