name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest  # Use Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        choco install docker-compose -y
        cmd /c "docker-compose --version"  # Run cmd commands using cmd /c

    - name: Set up Docker
      run: |
        docker --version
        cmd /c "docker-compose --version"  # Run cmd commands using cmd /c

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t ubuntu0new/simple-node-app:latest .
        docker push ubuntu0new/simple-node-app:latest

  deploy:
    runs-on: windows-latest  # Use Windows runner
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Kubectl
      run: |
        choco install kubernetes-cli -y

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml --validate=false
        kubectl apply -f service.yaml --validate=false
